import type { DrawingId, QuoteItem } from "@/components/quotations/types";

export type DrawingCatalogItem = {
  id: DrawingId;
  itemCode: string;
  productName: string;
  description: string;
  tags: string[];
  internal?: boolean;
  defaults: Omit<QuoteItem, "id">;
};

export const drawingCatalog: DrawingCatalogItem[] = [
  {
    id: "sliding-door-frame",
    itemCode: "FRAME-01",
    productName: "Reusable sliding door frame",
    description: "Frame-only module: left and right vertical frame pieces with top and bottom rails sitting flush between them.",
    tags: ["frame", "module", "sliding", "door", "4 panel", "2 tracks"],
    defaults: {
      itemCode: "FRAME-01",
      drawingId: "sliding-door-frame",
      productName: "Reusable sliding door frame",
      quantity: 1,
      widthMm: 3715,
      heightMm: 2795,
      panelCount: 4,
      trackCount: 2,
      aluminumColor: "White",
      glassType: "None",
      hardware: "Frame only",
      showLock: false,
      lockPosition: "right",
      viewDirection: "inside",
      location: "",
    },
  },
  {
    id: "fixed-door-module",
    itemCode: "FIX-01",
    productName: "Fixed door module",
    description: "Approved frame with one fixed door leaf fitted flush inside the frame opening.",
    tags: ["fixed", "module", "door", "leaf", "fix", "1 door", "1 track"],
    defaults: {
      itemCode: "FIX-01",
      drawingId: "fixed-door-module",
      productName: "Fixed door module",
      quantity: 1,
      widthMm: 3715,
      heightMm: 2795,
      panelCount: 1,
      trackCount: 1,
      aluminumColor: "White",
      glassType: "Clear tempered glass",
      hardware: "Frame plus fixed leaf",
      showLock: false,
      lockPosition: "right",
      viewDirection: "inside",
      location: "",
    },
  },
  {
    id: "fixed-two-door-module",
    itemCode: "FIX-02",
    productName: "Two fixed door one-track module",
    description: "Approved one-track frame with two equal fixed door leaves fitted flush inside the frame opening.",
    tags: ["fixed", "module", "sliding", "door", "leaf", "2 door", "1 track"],
    defaults: {
      itemCode: "FIX-02",
      drawingId: "fixed-two-door-module",
      productName: "Two fixed door one-track module",
      quantity: 1,
      widthMm: 3715,
      heightMm: 2795,
      panelCount: 2,
      trackCount: 1,
      aluminumColor: "White",
      glassType: "Clear tempered glass",
      hardware: "One-track frame plus two fixed leaves",
      showLock: false,
      lockPosition: "right",
      viewDirection: "inside",
      location: "",
    },
  },
  {
    id: "behind-track-left-slide-module",
    itemCode: "BEHIND-L-01",
    productName: "Behind door slides left module",
    description: "Approved frame with one fixed door on the left and one behind-track door on the right that slides left.",
    tags: ["behind track", "back track", "module", "sliding", "door", "slide left", "2 tracks"],
    defaults: {
      itemCode: "BEHIND-L-01",
      drawingId: "behind-track-left-slide-module",
      productName: "Behind door slides left module",
      quantity: 1,
      widthMm: 3715,
      heightMm: 2795,
      panelCount: 2,
      trackCount: 2,
      aluminumColor: "White",
      glassType: "Clear tempered glass",
      hardware: "Frame plus fixed and behind sliding leaves",
      showLock: false,
      lockPosition: "right",
      viewDirection: "inside",
      location: "",
    },
  },
  {
    id: "behind-track-right-slide-module",
    itemCode: "BEHIND-R-01",
    productName: "Behind door slides right module",
    description: "Approved frame with one behind-track door on the left that slides right behind one fixed door on the right.",
    tags: ["behind track", "back track", "module", "sliding", "door", "slide right", "2 tracks"],
    defaults: {
      itemCode: "BEHIND-R-01",
      drawingId: "behind-track-right-slide-module",
      productName: "Behind door slides right module",
      quantity: 1,
      widthMm: 3715,
      heightMm: 2795,
      panelCount: 2,
      trackCount: 2,
      aluminumColor: "White",
      glassType: "Clear tempered glass",
      hardware: "Frame plus fixed and behind sliding leaves",
      showLock: false,
      lockPosition: "right",
      viewDirection: "inside",
      location: "",
    },
  },
  {
    id: "four-panel-front-behind-module",
    itemCode: "SLIDE-04",
    productName: "Four door fixed and sliding set",
    description: "Four-door set with fixed doors at both sides and two behind-track center doors sliding outward.",
    tags: ["4 door", "four panel", "fixed", "behind track", "sliding", "door", "2 tracks"],
    defaults: {
      itemCode: "SLIDE-04",
      drawingId: "four-panel-front-behind-module",
      productName: "Four door fixed and sliding set",
      quantity: 1,
      widthMm: 3715,
      heightMm: 2795,
      panelCount: 4,
      trackCount: 2,
      aluminumColor: "White",
      glassType: "Clear tempered glass",
      hardware: "Frame with two fixed leaves and two behind sliding leaves",
      showLock: false,
      lockPosition: "right",
      viewDirection: "inside",
      location: "",
    },
  },
];
